changes: users can now select the repo they wish to delete from the display

diff --git a/.scpts/deleteRepo b/.scpts/deleteRepo
--- a/.scpts/deleteRepo
+++ b/.scpts/deleteRepo
@@ -28,6 +28,125 @@ function get_git_details()
 	fi
 }
 
+disp()
+{
+    page_size=9
+    total_repos=${#repo_names[@]}
+    num_pages=$(( (total_repos + page_size - 1) / page_size ))
+
+    page=1
+    while true; do
+        clear
+        echo "Available repositories in $GUSERNAME:"
+        echo "Page $page:"
+        
+        serial_number=0
+        for ((i = (page - 1) * page_size; i < page * page_size && i < total_repos; i++)); do
+            ((serial_number++))
+            echo "$serial_number. ${repo_names[i]}"
+            sleep 0.05
+        done
+
+        echo -e ""
+        if (( $page > 1 )); then
+            echo "[p] - Previous Page"
+        fi
+
+        if (( $page < $num_pages )); then
+            echo "[n] - Next Page"
+        fi
+		echo "[q] - quit"
+
+		selection=""
+        echo -e ""
+        read -n 1 -s -r -p "Enter the number corresponding to the repository you want to delete >>> " selection
+        echo -e "$selection"
+
+        if [[ "$selection" =~ [qQ] ]]; then
+			exiting
+		elif [[ "$selection" =~ [nN] && "$page" -lt "$num_pages" ]]; then
+            ((page++))
+        elif [[ "$selection" =~ [pP] && "$page" -gt 1 ]]; then
+            ((page--))
+        elif [[ "$selection" =~ ^[1-9]|[1-9][0-9]|[1-9][0-9][0-9]*$ && "$selection" -le "$serial_number" ]]; then
+            converted_selection="$(( ($page - 1) * $page_size + $((selection-1)) ))"
+            selected_repo=${repo_names_cleaned[$converted_selection]}
+            
+			echo -e ""
+            echo "You selected: $selected_repo"
+            echo -e ""
+            break
+        else
+            echo "Invalid selection."
+        fi
+    done
+}
+
+get_repo_name()
+{
+	echo ""
+	echo "Hold on ..."
+	echo ""
+    # users repo
+    if [[ "$GTOKEN" == *"ghp_"* ]]; then
+        echo -e ""
+    else
+        GTOKEN="ghp_$GTOKEN"
+    fi
+
+    public_response=$(curl -s "https://api.github.com/users/$GUSERNAME/repos?type=public&per_page=100")
+
+    private_response=$(curl -s -H "Authorization: token $GTOKEN" \
+    "https://api.github.com/user/repos?visibility=private")
+
+    if [[ "$public_response" == *"message"* && "$public_response" == *"Not Found"* ]]; then
+        echo "User $GUSERNAME not found on GitHub."
+        exit 1
+    fi
+
+    if [[ "$private_response" == *"message"* && "$private_response" == *"Bad credentials"* ]]; then
+        echo "Bad credentials. Make sure your GitHub token is valid and has the required permissions."
+        exit 1
+    fi
+
+    if [[ "$public_response" == "" || "$private_response" == "" ]]; then
+        echo -e "Could not connect to https://github.com/$GUSERNAME"
+        echo -e "Check your internet connection."
+        echo -e ""
+        exit 1
+    fi
+
+    public_resp=$(echo "$public_response" | grep -oP '"full_name": "\K[^"]+' | awk -F'/' '{print $2}')
+
+    private_resp=$(echo "$private_response" | grep -oP '"full_name": "\K[^"]+' | awk -F'/' '{print $2}')
+		
+    pub_arr=($public_resp)
+    pri_arr=($private_resp)
+
+    repo_names_cleaned=("${pub_arr[@]}" "${pri_arr[@]}")
+
+    for ((i=0; i<${#pub_arr[@]}; i++)); do
+        pub_arr[$i]="${pub_arr[$i]} (pub)"
+    done
+
+    for ((i=0; i<${#pri_arr[@]}; i++)); do
+        pri_arr[$i]="${pri_arr[$i]} (priv)"
+    done
+
+    repo_names=("${pub_arr[@]}" "${pri_arr[@]}")
+    disp
+    REPONAME="$selected_repo"
+
+	if [[ -z "$REPONAME" ]]; then
+		lines
+		echo -e "You can't clone a repo without a name..."
+		exiting
+	fi
+}
+
+
+
+
 # ENTRY-POINT
 
 # Kindly supply your Github Username and Personal Access token(without the "ghp_").
@@ -43,22 +162,25 @@ if [[ -z "$GUSERNAME" ]]; then
 	get_git_details
 fi
 
-if [[ -z "$REPONAME" ]]; then
-    echo -ne "\nPlease provide a repository name to delete in \"$GUSERNAME\" >>> "
-    read REPONAME
+get_repo_name
 
-    if [[ -z "$REPONAME" ]]; then
-	    echo -ne "\nYou can't delete a repo without a name..."
-        exiting
-    fi
-fi
-REPONAME=$(echo "$REPONAME" | sed 's/\/$//') #used to remove trailing "/" if user adds it
+# if [[ -z "$REPONAME" ]]; then
+#     echo -ne "\nPlease provide a repository name to delete in \"$GUSERNAME\" >>> "
+#     read REPONAME
+
+#     if [[ -z "$REPONAME" ]]; then
+# 	    echo -ne "\nYou can't delete a repo without a name..."
+#         exiting
+#     fi
+# fi
+# REPONAME=$(echo "$REPONAME" | sed 's/\/$//') #used to remove trailing "/" if user adds it
 
 EXISTENCE_CHECK_URL="https://api.github.com/repos/$GUSERNAME/$REPONAME"
 
-existence_check=$(curl -s -o /dev/null -w "%{http_code}" -u "$GUSERNAME:ghp_$GTOKEN" $EXISTENCE_CHECK_URL)
+existence_check=$(curl -s -o /dev/null -w "%{http_code}" -u "$GUSERNAME:$GTOKEN" $EXISTENCE_CHECK_URL)
 if [ $existence_check -eq 200 ]; then
     if [[ -z "$RESP" ]]; then
+        echo "NOTE: THIS ACTION IS NOT REVERSIBLE."
 	    echo -n "Are you sure you want to DELETE the repository \"$REPONAME\" from \"https://github.com/$GUSERNAME\"?... (y/n) >>> "
         read -n 1 -s -r RESP
 	    echo -e ""
@@ -73,7 +195,7 @@ if [ $existence_check -eq 200 ]; then
 
 	    elif [[ ${#RESP} =~ 1 && ("$RESP" =~ "y" || "$RESP" =~ "Y") ]]; then
 
-            response=$(curl -s -o /dev/null -w "%{http_code}:%{response_code}" -u "$GUSERNAME:ghp_$GTOKEN" -X DELETE $EXISTENCE_CHECK_URL)
+            response=$(curl -s -o /dev/null -w "%{http_code}:%{response_code}" -u "$GUSERNAME:$GTOKEN" -X DELETE $EXISTENCE_CHECK_URL)
             status=$?
 
             if [ $status -eq 0 ]; then
@@ -122,5 +244,5 @@ if [ -d "$REPONAME" ]; then
         echo "Deletion aborted."
     fi
 else
-    echo "Directory \"$REPONAME/\" does not exist locally."
+    echo "Directory \"$REPONAME/\" does not exist in the current directory."
 fi
