fixed startapp: fixed path to pymanage, refactored execution logic

diff --git a/.scpts/startapp b/.scpts/startapp
--- a/.scpts/startapp
+++ b/.scpts/startapp
@@ -16,7 +16,7 @@ if [[ -n "$check" ]]; then
 	fi
 fi
 
-command=$(cat $path1/pymanage)
+command=$(cat $path1/pymanage) # move this to pyfiles now
 command+="startapp"
 
 if [ "$#" != "1" ]; then
@@ -25,10 +25,58 @@ if [ "$#" != "1" ]; then
 elif [ "$#" -eq 1 ]; then
 	# echo "App name: $1"
 	command+=" $1"
-	$command
+	# echo "1111111111111111111"
+	echo ""
+	run_command="$(2>&1 $command)"
+	status_code="$?"
+	# echo "status: $status_code"
+	# echo "run_command: $run_command"
+	# echo "############# from bash #########################"
+	# echo $run_command | python3 $path1/pyfiles/process_more.py django
+	# echo "############# end from bash #########################"
+	if [[ "$status_code" == "1" && "$run_command" == *"ModuleNotFoundError"* ]]; then
+		module_error="$(echo $run_command | python3 $path1/pyfiles/process_more.py django)"
+		echo "Oopsi!"
+		echo "You have $module_error configured under INSTALLED_APPS in settings.py"
+		echo "Remove it completely and try again."
+		exit 1
+	fi
+	# echo "222222222222222222"
 	output="$(echo "$1 $0" | python3 $path1/pyfiles/configure_settings_py.py 2>&1)"
 	echo "$output"
 	echo ""
 	echo "..............................................."
 	echo "$1 app created successfully and configured in urls.py and under INSTALLED_APPS in settings.py"
 fi
+
+# status_code="$?"
+# 	# echo "status: $status_code"
+# 	# echo "run_command: $run_command"
+# 	echo "############### just print #######################"
+# 	newvar="django ${run_command}"
+# 	echo "the new var: $newvar"
+# 	echo "############### start #######################"
+# 	module_error="$(echo "$newvar" | python3 $path1/pyfiles/process_more.py)"
+# 	echo "############### new arg #######################"
+# 	exit 5
+# 	# echo "${run_command}django" | python3 $path1/pyfiles/process_more.py
+# 	# echo "############### at start #######################"
+# 	# echo "django $run_command" | python3 $path1/pyfiles/process_more.py
+# 	# echo "############### at end #######################"
+# 	# echo "$run_command" django | python3 $path1/pyfiles/process_more.py
+# 	# echo "################## end ####################"
+# 	# if [[ "$status_code" == "1" && "$run_command" == *"ModuleNotFoundError"* ]]; then
+# 	# 	module_error="$(echo "$newvar" | python3 $path1/pyfiles/process_more.py)"
+# 	# 	echo "Oopsi!"
+# 	# 	echo "You have not installed $module_error but used it in INSTALLED_APPS"
+# 	# 	echo "Or that this app exists under your INSTALLED_APPS in settings"
+# 	# 	echo "Remove it completely and try again or use a different app name"
+# 	# 	exit 1
+# 	# fi
+# 	# echo "222222222222222222"
+# 	output="$(echo "$1 $0" | python3 $path1/pyfiles/configure_settings_py.py 2>&1)"
+# 	echo "$output"
+# 	echo ""
+# 	echo "..............................................."
+# 	echo "$1 app created successfully and configured in urls.py and under INSTALLED_APPS in settings.py"
+# fi
